# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - summitConvertPDFAPI

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_5fdb8ef87ed6486e8122e6a32669b621 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_eb4d7eac73f54500b433fcb90607a957 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_5fdb8ef87ed6486e8122e6a32669b621 }}/thakae/latest:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'summitConvertPDFAPI'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_312e57c09c14439798e8f116908ad217 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_5fdb8ef87ed6486e8122e6a32669b621 }}/thakae/latest:${{ github.sha }}'